export const NEWS_SEND_REQUEST = "NEWS_SEND_REQUEST";
export const NEWS_SUCCESS_REQUEST = "NEWS_SUCCESS_REQUEST";
export const NEWS_FAILED_REQUEST = "NEWS_FAILED_REQUEST";
export const NEWS_NEXT_PAGE = "NEWS_NEXT_PAGE";
export const NEWS_PREVIOUS_PAGE = "NEWS_PREVIOUS_PAGE";
export const NEW_HIDE_ACTION = "NEw_HIDE_ACTION";
export const NEWS_INCREMENT_VOTE = "NEWS_INCREMENT_VOTE"